from setuptools import setup, find_packages

setup(
    name="dynamic-workforce-analyzer",
    version="0.1.0",
    description="A comprehensive career intelligence platform that tracks skill demands across industries and predicts future trends",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(),
    install_requires=[
        "numpy",
        "pandas",
        "scikit-learn",
        "matplotlib",
        "seaborn",
        "requests",
        "beautifulsoup4",
        "selenium",
        "scrapy",
        "playwright",
        "nltk",
        "spacy",
        "transformers",
        "gensim",
        "prophet",
        "statsmodels",
        "networkx",
        "pyvis",
        "xgboost",
        "lightgbm",
        "tensorflow",
        "torch",
        "flask",
        "dash",
        "plotly",
        "tqdm",
        "joblib",
        "python-dotenv",
    ],
    python_requires=">=3.8",
)